### ISSUE TITLE
Duplicate repo?

### ISSUE THREAD

**Issue by samglover** [IllinoisLegalAidOnline/docassemble-IlFeeWaiver#22]
This interview repo seems to be a duplicate of a [more active ILAO repo](https://github.com/IllinoisLegalAidOnline/docassemble-FeeWaiver). Unless there is a good reason to keep this repo around, I recommend we archive it.

**Comment by samglover** [comment]
@nonprofittechy @mnewsted

**Comment by nonprofittechy** [comment]
I think you're right--will let Matt confirm

**Comment by mnewsted** [comment]
Yes, this is another one that is duplicative. The authoritative/live
version is on ILAO's GitHub account.

There might also be an ILAOEFile package on the Suffolk GithHub that can be
archived.

Thanks!

*Matt Newsted (he/him/his) | Associate Director of Legal Tech | *
*Illinois Legal Aid Online <https://www.illinoislegalaid.org/>120 S LaSalle
St, Suite 900 | Chicago, IL 60603 | 312.977.9047 ext 127 <(312)%20977-9047>*

*ILAO proudly supports Pride Month with these LGBTQIA+ centered resources
<https://www.illinoislegalaid.org/legal-information/population/member-lgbtqia-community>.*

**Comment by samglover** [comment]
Thanks @mnewsted. Archiving.

**Comment by BryceStevenWilley** [comment]
(Just to resolve my confusion here):

This repo is used in the https://github.com/IllinoisLegalAidOnline/docassemble-AppearanceEfile, and has extra features that FeeWaiver doesn't have:

* splits out the fee waiver into a body and main part, so the fee waiver could be included in other interviews
* some extra EFiling integration

I'm guess that Matt eventually figured that out (since it's not archived anymore), but I had to look into things when there's a big note at the top of the Readme saying it's out of date and a duplicate.
